### ISSUE TITLE
GBIC on-the-fly mode with mRNA tracks fails in pack mode

### ISSUE THREAD

**Issue by rembart** [ucscGenomeBrowser/kent#20]
Hello, 
I observe a strange behavior in our ucsc genome browser (GBIC)

We have a  full-mirrored dm3 genome and run the ucsc in on-the-fly mode (-f), if you select a larger region (>1 million) in the top chromosome-navigation ("jump to new region") the whole ucsc browser stucks and sometimes displays an error: 

"Encountered a network error. Please try again. If the problem persists, please check your network connection." 

and these lines in the httpd error log:

[Sun May 05 14:24:34.869274 2019] [cgi:warn] [pid 76103] [client 10.42.211.120:62659] AH01220: Timeout waiting for output from CGI script /usr/local/apache/cgi-bin/hgTracks, referer: https://ucsc.mysite.com/cgi-bin/hgTracks?db=dm3&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr2L%3A15135875%2D20656016&hgsid=753_juILa2OSPbgbUsAhi7fSwb5Mirel
[Sun May 05 14:24:34.869382 2019] [core:error] [pid 76103] (70007)The timeout specified has expired: [client 10.42.211.120:62659] AH00574: ap_content_length_filter: apr_bucket_read() failed, referer: https://ucsc.mysite.com/cgi-bin/hgTracks?db=dm3&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr2L%3A15135875%2D20656016&hgsid=753_juILa2OSPbgbUsAhi7fSwb5Mirel

That only happens if the track "D. melanogaster mRNAs" is set to "pack", dense mode always works.

if the ucsc is in the offline mode (-o) everythings works perfectly fine, for both dense and pack. 

Is it an intended behavior that the browser tries to download always the mRNA tracks from upstream even if they are mirrored?

(I already got the newest gbic-script, cgi-software and genome updates - it had no effect on the behavior)

Best,
Klaus

**Comment by maximilianh** [comment]
It sounds like there is a table missing and possibly this is a table related to the mRNA. Could we have a look at your Apache error log?

**Comment by rembart** [comment]
Hello and thanks for the fast response!
I attached 2 apache_error logs with sql-debug turned on:
the first is in the on-the-fly mode (the application crashed in the end) 
the second is in the offline mode (everything worked)

Best Klaus

[error_log.zip](https://github.com/ucscGenomeBrowser/kent/files/3154796/error_log.zip)

**Comment by maximilianh** [comment]
Hi Klaus, I'm sorry for the late reply, Github issues are not in our ticket tracking system, otherwise this would have not been dropped for so long. I don't have a clear answer for you yet, but some ideas. According to the log, the hgFixed database is not on your server, but by default, the GBIC script copies it over. Did you install your mirror with the -t option? Shall I send you the rsync command to mirror the hgFixed database?

**Comment by rembart** [comment]
Hello, 
thanks for your help - I was able to fix the database files, now everything works fine!
For some reason the hgFixed database had a non-system user (uid 497 / gid 495) as owner set - maybe a failed run of the rsync/update script in the past. 

Thanks again for your help!
Best,
Klaus

**Comment by maximilianh** [comment]
Hm, yes, this happens if you ctrl-c the script during the rsync, it will
leave behind a half-written directory and the access rights will be off.

I'm not sure what we could do to avoid this... I can look at the rsync
options, but I doubt there is something we can do without rewriting the
whole rsyncing...

>
