### ISSUE TITLE
twoBitToFa: Can only handle version 0 of this file. This is version 1

### ISSUE THREAD

**Issue by AlisaGU** [ucscGenomeBrowser/kent#67]
Hi, 
Due to the large size of my genome, i had to create the 2 bit file by `faToTwoBit -long`. However, twoBitToFa crushed and showed that `Can only handle version 0 of this file. This is version 1`
I have replaced the old version (2020) by the [latest](http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/twoBitToFa), but it didn't work.

Do you know the reason?

Best regards

**Comment by ucscbrianlee** [comment]
Hi,

Thank you for using the UCSC Genome Browser and your question about using the faToTwoBit -long option for larger genomes and the reverse twoBitToFa command. Your question has been answered on the UCSC mailing-list: https://groups.google.com/a/soe.ucsc.edu/g/genome/c/iI-oubRg0YM/m/xo3xeiF6CAAJ

Please use the UCSC mailing-list for such questions, and follow-up questions, instead of our GitHub account.

We have two mailing lists, one which is a publicly archived list that can be searched for previous answers, send questions to that list at [genome@soe.ucsc.edu](mailto:genome@soe.ucsc.edu). If your questions have sensitive information, you can instead use [genome-www@soe.ucsc.edu](mailto:genome-www@soe.ucsc.edu), and our internal team will have a chance to respond, but the correspondence does not become part of the public list.

All the best,
